### ISSUE TITLE
关于ngx_httpc_connect与ngx_tcpclient_connectfailed 

### ISSUE THREAD

**Issue by stone-wind** [AlexWoo/ngx_tcpclient_module#1]
您好，我使用过1213号的版本，有两个可能的问题向您反馈一下：
1、ngx_httpc_connect中调用ngx_tcp_connect(tc)时，ngx_tcp_connect无返回值判断是否成功。当ngx_tcp_connect函数中失败调用了ngx_tcpclient_connectfailed，这会导致ngx_httpc_connect返回的新连接(ngx_tcpclient_connection_t *)c实际有可能已经被销毁（c->pool），因此上层做if (NULL == c) 实际无法得到正确判断，会导致接下来的ngx_httpc_send_request等操作均可能有段错误；
2、ngx_tcpclient_connectfailed 函数中:
1170:ngx_client_close_connection(tc, 1);
         if (tc->actions.onclose) {
             tc->actions.onclose(tc);
         }
     ngx_client_close_connection(tc, 1);被调用后，且tc->actions.onclose = ngx_httpc_close时。ngx_httpc_close调用ngx_httpc_close_connection，ngx_httpc_close_connection中队tc的访问会产生段错误，且ngx_httpc_close_connection中又调用了一次ngx_tcp_close(tc)---->ngx_client_close_connection(tc, 1);

望知悉。

**Comment by AlexWoo** [comment]
感谢反馈，后续版本会修复
